# Generated by Django 4.2.27 on 2026-01-23 13:10

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_add_location_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerContract',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('initial_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_plan_months', models.PositiveIntegerField(default=0)),
                ('status', django_fsm.FSMField(choices=[('reserved', 'Reservado'), ('signed', 'Firmado'), ('active', 'Activo'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='reserved', max_length=20, protected=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Buyer Contract',
                'verbose_name_plural': 'Buyer Contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('title_es', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.TextField()),
                ('description_es', models.TextField(blank=True)),
                ('developer_name', models.CharField(max_length=255)),
                ('developer_logo', models.ImageField(blank=True, null=True, upload_to='projects/developer_logos/')),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('total_units', models.PositiveIntegerField(default=0)),
                ('sold_units', models.PositiveIntegerField(default=0)),
                ('available_units', models.PositiveIntegerField(default=0)),
                ('price_range_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price in USD', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('price_range_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price in USD', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('construction_start_date', models.DateField(blank=True, null=True)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('master_plan_url', models.URLField(blank=True)),
                ('brochure_url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/covers/%Y/%m/')),
                ('status', django_fsm.FSMField(choices=[('draft', 'Borrador'), ('presale', 'Pre-venta'), ('under_construction', 'En Construcción'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='draft', max_length=25, protected=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='common.location')),
                ('manager', models.ForeignKey(blank=True, help_text='Project Admin who manages this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellableAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(help_text='e.g. A-301, P-05', max_length=50)),
                ('asset_type', models.CharField(choices=[('apartment', 'Apartamento'), ('parking', 'Estacionamiento'), ('storage', 'Maletero'), ('commercial', 'Comercial'), ('land_lot', 'Lote de Terreno')], default='apartment', max_length=20)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', django_fsm.FSMField(choices=[('available', 'Disponible'), ('reserved', 'Reservado'), ('sold', 'Vendido'), ('delivered', 'Entregado')], default='available', max_length=20, protected=True)),
                ('floor_plan_url', models.URLField(blank=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='projects.project')),
            ],
            options={
                'verbose_name': 'Sellable Asset',
                'verbose_name_plural': 'Sellable Assets',
                'ordering': ['asset_type', 'identifier'],
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('title_es', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('content_es', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/updates/%Y/%m/')),
                ('is_public', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_updates', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Update',
                'verbose_name_plural': 'Project Updates',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('title_es', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('description_es', models.TextField(blank=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('percentage', models.PositiveIntegerField(default=0, help_text='Percentage contribution to overall progress')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('delayed', 'Retrasado')], default='pending', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Milestone',
                'verbose_name_plural': 'Project Milestones',
                'ordering': ['order', 'target_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/gallery/%Y/%m/')),
                ('image_url', models.URLField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentScheduleItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_date', models.DateField()),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('concept', models.CharField(choices=[('initial', 'Inicial'), ('monthly', 'Mensual'), ('milestone', 'Hito'), ('final', 'Final'), ('other', 'Otro')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('overdue', 'Vencido'), ('waived', 'Exonerado')], default='pending', max_length=20)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='projects.buyercontract')),
            ],
            options={
                'verbose_name': 'Payment Schedule Item',
                'verbose_name_plural': 'Payment Schedule Items',
                'ordering': ['due_date'],
            },
        ),
        migrations.AddField(
            model_name='buyercontract',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='projects.sellableasset'),
        ),
        migrations.AddField(
            model_name='buyercontract',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyer_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sellableasset',
            index=models.Index(fields=['project', 'status'], name='projects_se_project_fdc808_idx'),
        ),
        migrations.AddIndex(
            model_name='sellableasset',
            index=models.Index(fields=['asset_type'], name='projects_se_asset_t_97220b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sellableasset',
            unique_together={('project', 'identifier')},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'city'], name='projects_pr_status_4b65b9_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['price_range_min', 'price_range_max'], name='projects_pr_price_r_1887cd_idx'),
        ),
        migrations.AddConstraint(
            model_name='buyercontract',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['reserved', 'signed', 'active'])), fields=('asset',), name='unique_active_contract_per_asset'),
        ),
    ]
