# Generated by Django 4.2.27 on 2026-01-13 17:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_es', models.CharField(blank=True, help_text='Spanish name if different', max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('location_type', models.CharField(choices=[('island', 'Isla'), ('city', 'Ciudad'), ('region', 'Región'), ('beach', 'Playa'), ('mountain', 'Montaña')], default='city', max_length=20)),
                ('state', models.CharField(help_text='Venezuelan state (e.g., Nueva Esparta)', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_es', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, help_text='Representative image for this location')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured locations')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent location (e.g., state for a city)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='common.location')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
