# Generated by Django 4.2.27 on 2026-01-13 03:28

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.TextField()),
                ('description_es', models.TextField(blank=True, help_text='Spanish description')),
                ('property_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('villa', 'Villa'), ('penthouse', 'Penthouse'), ('townhouse', 'Townhouse'), ('land', 'Land'), ('commercial', 'Commercial')], default='house', max_length=20)),
                ('listing_type', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], default='sale', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('pending', 'Pending Review'), ('sold', 'Sold'), ('rented', 'Rented'), ('inactive', 'Inactive')], default='draft', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('price_negotiable', models.BooleanField(default=False)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, help_text='Area in square meters', max_digits=10, null=True)),
                ('lot_size_sqm', models.DecimalField(blank=True, decimal_places=2, help_text='Lot size in square meters', max_digits=10, null=True)),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
                ('parking_spaces', models.PositiveIntegerField(default=0)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='Venezuela', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of features like pool, garden, etc.')),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_new_construction', models.BooleanField(default=False)),
                ('is_beachfront', models.BooleanField(default=False)),
                ('is_investment_opportunity', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='properties/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_main', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
                'ordering': ['order', '-is_main', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedProperty',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Property',
                'verbose_name_plural': 'Saved Properties',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'property')},
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'listing_type'], name='properties__status_b35a4c_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price'], name='properties__price_32e7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'state'], name='properties__city_fe3b3f_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type'], name='properties__propert_5c7790_idx'),
        ),
    ]
