# Generated by Django 4.2.27 on 2026-01-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertyimage_image_url_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('beach_apartment', 'Beach Apartment'), ('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('penthouse', 'Penthouse'), ('finca', 'Finca / Country Estate'), ('townhouse', 'Townhouse'), ('beach_house', 'Beach House'), ('land', 'Land'), ('commercial', 'Commercial')], default='house', max_length=20),
        ),
    ]
