# Generated by Django 4.2.27 on 2026-01-13 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_add_location_model'),
        ('properties', '0003_update_property_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes for admins'),
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Custom location/destination for this property', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='common.location'),
        ),
        migrations.AddField(
            model_name='property',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (if rejected)'),
        ),
        migrations.AddField(
            model_name='property',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the listing was reviewed', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who reviewed this listing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='When the agent submitted for review', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('pending_review', 'En Revisión'), ('active', 'Activa'), ('rejected', 'Rechazada'), ('inactive', 'Desactivada'), ('sold', 'Vendida'), ('rented', 'Alquilada')], default='draft', max_length=20),
        ),
    ]
