# Generated by Django 4.2.27 on 2026-01-13 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_agent_type_user_bio_es_user_city_user_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_referrer',
            field=models.BooleanField(default=False, help_text='Can this user refer new agents to the platform?'),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_date',
            field=models.DateTimeField(blank=True, help_text='When the agent was referred', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_fee_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('waived', 'Waived'), ('na', 'Not Applicable')], default='na', help_text='Status of referral fee payment', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_notes',
            field=models.TextField(blank=True, help_text='Notes about the referral'),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='Staff member or agent who referred this user', limit_choices_to={'is_referrer': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
    ]
