# Generated by Django 4.2.27 on 2026-01-13 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agent_type',
            field=models.CharField(blank=True, choices=[('individual', 'Independent Realtor'), ('company', 'Real Estate Company')], default='individual', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='parent_company',
            field=models.ForeignKey(blank=True, help_text='Company this agent works for', limit_choices_to={'agent_type': 'company'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
