# Generated by Django 4.2.27 on 2026-01-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_broker_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('agent', 'Real Estate Agent'), ('project_admin', 'Project Administrator'), ('buyer', 'Buyer')], default='buyer', max_length=20),
        ),
    ]
